export default (staticData = [
    {
      id: 1,
      name: "Satya Narayana Pooja, Ayushya Homa",
      category: 'pooja',
      subcategory: 'pooja',
      area:'Shakambari Nagar',
      price: 1000,
      date: "17-06-2020",
      time: "9 AM",
      bookingId: "A23231",
      address:"No.18, 1st Main, Shakambari Nagar, Opposite to BSK Temple, Bangalore - 560070",
      contact:"Paneendra Gautham",
      type:"Labor Contract",
      status:"pending",
      userType:"purohit"
    },
    {
      id: 2,
      name: "Dhanvantari Homa",
      category: 'pooja',
      subcategory: 'homa',
      area:'Some Area',
      price: 2000,
      date: "19.02.2020",
      time: "10 AM",
      bookingId: "B36181",
      address:"No.18, 1st Main, Shakambari Nagar, Opposite to BSK Temple, Bangalore - 560070",
      contact:"Paneendra Gautham",
      type:"Full Contract",
      status:"completed",
      userType:"purohit"
    },
    {
      id: 3,
      name: "Navagraha Homa",
      category: 'pooja',
      subcategory: 'homa',
      area:'Some Area',
      price: 2000,
      date: "02.10.2019",
      time: "10 AM",
      bookingId: "B36181",
      address:"No.18, 1st Main, Shakambari Nagar, Opposite to BSK Temple, Bangalore - 560070",
      contact:"Paneendra Gautham",
      type:"Full Contract",
      status:"completed",
      userType:"purohit"
    },
    {
      id: 4,
      name: "Mrutyunjaya Homa",
      category: 'pooja',
      subcategory: 'homa',
      area:'Some Area',
      price: 2000,
      date: "23.06.2020",
      time: "10 AM",
      bookingId: "B36181",
      address:"No.18, 1st Main, Shakambari Nagar, Opposite to BSK Temple, Bangalore - 560070",
      contact:"Paneendra Gautham",
      type:"Full Contract",
      status:"accepted",
      userType:"purohit"
    },
    {
      id: 5,
      name: "Satya Narayana Pooja",
      category: 'pooja',
      subcategory: 'pooja',
      area:'Some Area',
      price: 1000,
      date: "16.06.2020",
      time: "9 AM",
      bookingId: "A23231",
      address:"No.18, 1st Main, Shakambari Nagar, Opposite to BSK Temple, Bangalore - 560070",
      contact:"Paneendra Gautham",
      type:"Full Contract",
      status:"accepted",
      userType:"purohit"
    },
    {
      id: 6,
      name: "Dhanvantari Homa",
      category: 'pooja',
      subcategory: 'homa',
      area:'Hosakerehalli',
      price: 2000,
      date: "19.02.2020",
      time: "10 AM",
      bookingId: "B36181",
      address:"No.18, 1st Main, Shakambari Nagar, Opposite to BSK Temple, Bangalore - 560070",
      contact:"Paneendra Gautham",
      type:"Full Contract",
      status:"pending",
      userType:"purohit"
    },
    {
      id: 7,
      name: "Navagraha Homa",
      category: 'pooja',
      subcategory: 'homa',
      area:'Some Area',
      price: 2000,
      date: "02.10.2019",
      time: "10 AM",
      bookingId: "B36181",
      address:"No.18, 1st Main, Shakambari Nagar, Opposite to BSK Temple, Bangalore - 560070",
      contact:"Paneendra Gautham",
      type:"Full Contract",
      status:"completed",
      userType:"purohit"
    },
    {
      id: 8,
      name: "Mrutyunjaya Homa",
      category: 'pooja',
      subcategory: 'homa',
      area:'Some Area',
      price: 2000,
      date: "9.07.2020",
      time: "10 AM",
      bookingId: "B36181",
      address:"No.18, 1st Main, Shakambari Nagar, Opposite to BSK Temple, Bangalore - 560070",
      contact:"Paneendra Gautham",
      type:"Full Contract",
      status:"completed",
      userType:"purohit"
    },
    {
      id: 9,
      name: "Mrutyunjaya Homa",
      category: 'pooja',
      subcategory: 'homa',
      area:'Some Area',
      price: 2000,
      date: "09-07-2020",
      time: "10 AM",
      bookingId: "B36181",
      address:"No.18, 1st Main, Shakambari Nagar, Opposite to BSK Temple, Bangalore - 560070",
      contact:"Paneendra Gautham",
      type:"Labor Contract",
      status:"pending",
      userType:"customer"
    },
    {
      id: 10,
      name: "Pavamana Homa",
      category: 'pooja',
      subcategory: 'homa',
      area:'Some Area',
      price: 2000,
      date: "29-07-2020",
      time: "10 AM",
      bookingId: "B36181",
      address:"No.18, 1st Main, Shakambari Nagar, Opposite to BSK Temple, Bangalore - 560070",
      contact:"Paneendra Gautham",
      type:"Full Contract",
      status:"pending",
      userType:"customer"
    },
    {
      id: 10,
      name: "Pavamana Homa",
      category: 'pooja',
      subcategory: 'homa',
      area:'Some Area',
      price: 2000,
      date: "29-07-2020",
      time: "10 AM",
      bookingId: "B36181",
      address:"No.18, 1st Main, Shakambari Nagar, Opposite to BSK Temple, Bangalore - 560070",
      contact:"Paneendra Gautham",
      type:"Full Contract",
      status:"accepted",
      userType:"customer"
    },
    
  ]);
  