/*--- ERRORS ---*/
export const GET_ERRORS = 'GET_ERRORS';

/*--- AUTH ---*/
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

/*--- GET DISTRICT OR CITY ---*/
export const GET_DISTRICT_OR_CITY = 'GET_DISTRICT_OR_CITY';

/*--- GET AREAS ---*/
export const GET_AREAS = 'GET_AREAS';

/*--- GET CASTE ---*/
export const GET_CASTES = 'GET_CASTES';

/*--- UPCOMING FESTIVALS ---*/
export const UPCOMING_FESTIVALS = 'UPCOMING_FESTIVALS';

/*--- SERVICE LIST ---*/
export const GET_SERVICE_LIST = 'GET_SERVICE_LIST';

/*--- FILTER SERVICES ---*/
export const POOJA_SERVICES = 'POOJA_SERVICES';
export const HOMA_SERVICES = 'HOMA_SERVICES';
export const FUNCTION_SERVICES = 'FUNCTION_SERVICES';
export const SELECTED_CATEGORY = 'SELECTED_CATEGORY';
export const FILTER_CATEGORY = 'FILTER_CATEGORY';

/*--- SEARCH SERVICES ---*/
export const SEARCH_SERVICES = 'SEARCH_SERVICES';

/*--- ADD TO BOOKING CART ---*/
export const ADD_TO_BOOKING_CART = 'ADD_TO_BOOKING_CART';

/*--- DELETE FROM BOOKING CART ---*/
export const DELETE_FROM_BOOKING_CART = 'DELETE_FROM_BOOKING_CART'