/*--- ERRORS ---*/
export const GET_ERRORS = 'GET_ERRORS';

/*--- AUTH ---*/
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

/*--- SERVICE LIST ---*/
export const GET_SERVICE_LIST = 'GET_SERVICE_LIST';

/*--- SEARCH OR FILTER SERVICES ---*/
export const POOJA_SERVICES = 'POOJA_SERVICES';
export const HOMA_SERVICES = 'HOMA_SERVICES';
export const FUNCTION_SERVICES = 'FUNCTION_SERVICES';


export const SEARCH_SERVICES = 'SEARCH_SERVICES';

export const SELECTED_CATEGORY = 'SELECTED_CATEGORY';

export const FILTER_CATEGORY = 'FILTER_CATEGORY';