/*--- ERRORS ---*/
export const GET_ERRORS = 'GET_ERRORS';

/*--- Register New User ---*/
export const REGISTER_NEW_LOADING = 'REGISTER_NEW_LOADING';
export const REGISTER_NEW_USER = 'REGISTER_NEW_USER';

/*--- AUTH ---*/
export const SET_AUTH_LOADING = 'SET_AUTH_LOADING'
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

/*--- GET DISTRICT OR CITY ---*/
export const GET_DISTRICT_OR_CITY = 'GET_DISTRICT_OR_CITY';

/*--- GET AREAS ---*/
export const GET_AREAS = 'GET_AREAS';

/*--- GET CASTE ---*/
export const GET_CASTES = 'GET_CASTES';

/*--- UPCOMING FESTIVALS ---*/
export const UPCOMING_FESTIVALS = 'UPCOMING_FESTIVALS';

/*--- SERVICE LIST ---*/
export const GET_SERVICE_LIST = 'GET_SERVICE_LIST';

/*--- FILTER SERVICES ---*/
export const POOJA_SERVICES = 'POOJA_SERVICES';
export const HOMA_SERVICES = 'HOMA_SERVICES';
export const FUNCTION_SERVICES = 'FUNCTION_SERVICES';

/*--- SEARCH OR FILTER SERVICES FOR COOK ---*/
export const BREAKFAST_SERVICES = 'BREAKFAST_SERVICES';
export const LUNCH_SERVICES = 'LUNCH_SERVICES';
export const SNACKS_SERVICES = 'SNACKS_SERVICES';
export const DINNER_SERVICES = 'DINNER_SERVICES';

export const SELECTED_CATEGORY = 'SELECTED_CATEGORY';
export const FILTER_CATEGORY = 'FILTER_CATEGORY';

/*--- SEARCH SERVICES ---*/
export const SEARCH_SERVICES = 'SEARCH_SERVICES';

/*--- BOOKING CART ---*/
export const ADD_TO_BOOKING_CART = 'ADD_TO_BOOKING_CART';
export const DELETE_FROM_BOOKING_CART = 'DELETE_FROM_BOOKING_CART';
export const BOOKING_CART_STRUCTURE = 'BOOKING_CART_STRUCTURE';
export const BOOKING_CART_STRUCTURE_SELECTED_DATE = 'BOOKING_CART_STRUCTURE_SELECTED_DATE';
export const ADD_TIME_TO_STRUCTURE_SELECTED_DATE = 'ADD_TIME_TO_STRUCTURE_SELECTED_DATE';